# Generated by Django 2.0.6 on 2018-07-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet_me', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='tag',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='tag',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='slot',
            name='tag',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
